package arjology

import org.apache.spark.sql.types.{StringType, FloatType, StructType, StructField, IntegerType}
import org.apache.spark.sql.DataFrame
import org.apache.spark.ml.feature.StringIndexer

object schema {

  val trainSchemaHeader = StructType(
    StructField("SK_ID_CURR", IntegerType, nullable = true) ::
      StructField("TARGET", FloatType, nullable = true) ::
      Nil
  )

  val testSchemaHeader = StructType(
    StructField("SK_ID_CURR", IntegerType, nullable = true) ::
      Nil
  )

  val schemaPart0 = StructType(
    StructField("NAME_CONTRACT_TYPE", StringType, nullable = true) ::
      StructField("CODE_GENDER", StringType, nullable = true) ::
      StructField("FLAG_OWN_CAR", StringType, nullable = true) ::
      StructField("FLAG_OWN_REALTY", StringType, nullable = true) ::
      StructField("CNT_CHILDREN", FloatType, nullable = true) ::
      StructField("AMT_INCOME_TOTAL", FloatType, nullable = true) ::
      StructField("AMT_CREDIT", FloatType, nullable = true) ::
      StructField("AMT_ANNUITY", FloatType, nullable = true) ::
      StructField("NAME_TYPE_SUITE", StringType, nullable = true) ::
      StructField("NAME_INCOME_TYPE", StringType, nullable = true) ::
      StructField("NAME_EDUCATION_TYPE", StringType, nullable = true) ::
      StructField("NAME_FAMILY_STATUS", StringType, nullable = true) ::
      StructField("NAME_HOUSING_TYPE", StringType, nullable = true) ::
      StructField("REGION_POPULATION_RELATIVE", FloatType, nullable = true) ::
      StructField("DAYS_BIRTH", FloatType, nullable = true) ::
      StructField("DAYS_EMPLOYED", FloatType, nullable = true) ::
      StructField("DAYS_REGISTRATION", FloatType, nullable = true) ::
      StructField("DAYS_ID_PUBLISH", FloatType, nullable = true) ::
      StructField("OWN_CAR_AGE", FloatType, nullable = true) ::
      StructField("FLAG_MOBIL", FloatType, nullable = true) ::
      StructField("FLAG_EMP_PHONE", FloatType, nullable = true) ::
      StructField("FLAG_WORK_PHONE", FloatType, nullable = true) ::
      StructField("FLAG_CONT_MOBILE", FloatType, nullable = true) ::
      StructField("FLAG_PHONE", FloatType, nullable = true) ::
      StructField("FLAG_EMAIL", FloatType, nullable = true) ::
      StructField("OCCUPATION_TYPE", StringType, nullable = true) ::
      StructField("REGION_RATING_CLIENT", FloatType, nullable = true) ::
      StructField("WEEKDAY_APPR_PROCESS_START", StringType, nullable = true) ::
      StructField("HOUR_APPR_PROCESS_START", FloatType, nullable = true) ::
      StructField("REG_REGION_NOT_LIVE_REGION", FloatType, nullable = true) ::
      StructField("REG_REGION_NOT_WORK_REGION", FloatType, nullable = true) ::
      StructField("REG_CITY_NOT_LIVE_CITY", FloatType, nullable = true) ::
      StructField("REG_CITY_NOT_WORK_CITY", FloatType, nullable = true) ::
      StructField("ORGANIZATION_TYPE", StringType, nullable = true) ::
      StructField("EXT_SOURCE_1", FloatType, nullable = true) ::
      StructField("EXT_SOURCE_2", FloatType, nullable = true) ::
      StructField("EXT_SOURCE_3", FloatType, nullable = true) ::
      StructField("APARTMENTS_AVG", FloatType, nullable = true) ::
      StructField("BASEMENTAREA_AVG", FloatType, nullable = true) ::
      StructField("YEARS_BEGINEXPLUATATION_AVG", FloatType, nullable = true) ::
      StructField("YEARS_BUILD_AVG", FloatType, nullable = true) ::
      StructField("COMMONAREA_AVG", FloatType, nullable = true) ::
      StructField("ENTRANCES_AVG", FloatType, nullable = true) ::
      StructField("FLOORSMAX_AVG", FloatType, nullable = true) ::
      StructField("FLOORSMIN_AVG", FloatType, nullable = true) ::
      StructField("LANDAREA_AVG", FloatType, nullable = true) ::
      StructField("NONLIVINGAPARTMENTS_AVG", FloatType, nullable = true) ::
      StructField("NONLIVINGAREA_AVG", FloatType, nullable = true) ::
      StructField("FONDKAPREMONT_MODE", StringType, nullable = true) ::
      StructField("HOUSETYPE_MODE", StringType, nullable = true) ::
      StructField("WALLSMATERIAL_MODE", StringType, nullable = true) ::
      StructField("EMERGENCYSTATE_MODE", StringType, nullable = true) ::
      StructField("OBS_30_CNT_SOCIAL_CIRCLE", FloatType, nullable = true) ::
      StructField("DEF_30_CNT_SOCIAL_CIRCLE", FloatType, nullable = true) ::
      StructField("DAYS_LAST_PHONE_CHANGE", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_2", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_3", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_4", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_5", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_6", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_7", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_8", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_9", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_10", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_11", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_12", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_13", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_14", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_15", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_16", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_17", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_18", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_19", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_20", FloatType, nullable = true) ::
      StructField("FLAG_DOCUMENT_21", FloatType, nullable = true) ::
      Nil)

  val schemaPart1 = StructType(
    StructField("AMT_REQ_CREDIT_BUREAU_HOUR", FloatType, nullable = true) ::
      StructField("AMT_REQ_CREDIT_BUREAU_DAY", FloatType, nullable = true) ::
      StructField("AMT_REQ_CREDIT_BUREAU_WEEK", FloatType, nullable = true) ::
      StructField("AMT_REQ_CREDIT_BUREAU_MON", FloatType, nullable = true) ::
      StructField("AMT_REQ_CREDIT_BUREAU_QRT", FloatType, nullable = true) ::
      StructField("AMT_REQ_CREDIT_BUREAU_YEAR", FloatType, nullable = true) ::
      StructField("previous_loan_counts", FloatType, nullable = true) ::
      StructField("CREDIT_ACTIVE_Active_count", FloatType, nullable = true) ::
      StructField("CREDIT_ACTIVE_Active_count_norm", FloatType, nullable = true) ::
      StructField("CREDIT_ACTIVE_Bad_debt_count", FloatType, nullable = true) ::
      StructField("CREDIT_ACTIVE_Closed_count", FloatType, nullable = true) ::
      StructField("CREDIT_ACTIVE_Closed_count_norm", FloatType, nullable = true) ::
      StructField("CREDIT_ACTIVE_Sold_count", FloatType, nullable = true) ::
      StructField("CREDIT_ACTIVE_Sold_count_norm", FloatType, nullable = true) ::
      StructField("CREDIT_CURRENCY_currency_1_count_norm", FloatType, nullable = true) ::
      StructField("CREDIT_CURRENCY_currency_2_count", FloatType, nullable = true) ::
      StructField("CREDIT_CURRENCY_currency_2_count_norm", FloatType, nullable = true) ::
      StructField("CREDIT_CURRENCY_currency_3_count", FloatType, nullable = true) ::
      StructField("CREDIT_CURRENCY_currency_3_count_norm", FloatType, nullable = true) ::
      StructField("CREDIT_CURRENCY_currency_4_count", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Another_type_of_loan_count", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Another_type_of_loan_count_norm", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Car_loan_count", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Car_loan_count_norm", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Cash_loan__non_earmarked__count", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Consumer_credit_count_norm", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Credit_card_count", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Credit_card_count_norm", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Interbank_credit_count", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Loan_for_business_development_count", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Loan_for_business_development_count_norm", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Loan_for_purchase_of_shares__margin_lending__count", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Loan_for_the_purchase_of_equipment_count", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Loan_for_the_purchase_of_equipment_count_norm", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Loan_for_working_capital_replenishment_count", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Loan_for_working_capital_replenishment_count_norm", FloatType, nullable = true) ::
      Nil)

  val schemaPart2 = StructType(
      StructField("CREDIT_TYPE_Microloan_count", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Microloan_count_norm", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Mobile_operator_loan_count", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Mortgage_count", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Mortgage_count_norm", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Real_estate_loan_count", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Real_estate_loan_count_norm", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Unknown_type_of_loan_count", FloatType, nullable = true) ::
      StructField("CREDIT_TYPE_Unknown_type_of_loan_count_norm", FloatType, nullable = true) ::
      StructField("bureau_DAYS_CREDIT_mean", FloatType, nullable = true) ::
      StructField("bureau_DAYS_CREDIT_max", FloatType, nullable = true) ::
      StructField("bureau_DAYS_CREDIT_sum", FloatType, nullable = true) ::
      StructField("bureau_CREDIT_DAY_OVERDUE_mean", FloatType, nullable = true) ::
      StructField("bureau_CREDIT_DAY_OVERDUE_max", FloatType, nullable = true) ::
      StructField("bureau_CREDIT_DAY_OVERDUE_min", FloatType, nullable = true) ::
      StructField("bureau_DAYS_CREDIT_ENDDATE_mean", FloatType, nullable = true) ::
      StructField("bureau_DAYS_CREDIT_ENDDATE_max", FloatType, nullable = true) ::
      StructField("bureau_DAYS_CREDIT_ENDDATE_min", FloatType, nullable = true) ::
      StructField("bureau_DAYS_ENDDATE_FACT_mean", FloatType, nullable = true) ::
      StructField("bureau_DAYS_ENDDATE_FACT_max", FloatType, nullable = true) ::
      StructField("bureau_AMT_CREDIT_MAX_OVERDUE_count", FloatType, nullable = true) ::
      StructField("bureau_AMT_CREDIT_MAX_OVERDUE_mean", FloatType, nullable = true) ::
      StructField("bureau_CNT_CREDIT_PROLONG_mean", FloatType, nullable = true) ::
      StructField("bureau_CNT_CREDIT_PROLONG_max", FloatType, nullable = true) ::
      StructField("bureau_CNT_CREDIT_PROLONG_min", FloatType, nullable = true) ::
      StructField("bureau_AMT_CREDIT_SUM_mean", FloatType, nullable = true) ::
      StructField("bureau_AMT_CREDIT_SUM_min", FloatType, nullable = true) ::
      StructField("bureau_AMT_CREDIT_SUM_DEBT_mean", FloatType, nullable = true) ::
      StructField("bureau_AMT_CREDIT_SUM_DEBT_max", FloatType, nullable = true) ::
      StructField("bureau_AMT_CREDIT_SUM_DEBT_min", FloatType, nullable = true) ::
      StructField("bureau_AMT_CREDIT_SUM_LIMIT_mean", FloatType, nullable = true) ::
      StructField("bureau_AMT_CREDIT_SUM_LIMIT_max", FloatType, nullable = true) ::
      StructField("bureau_AMT_CREDIT_SUM_LIMIT_min", FloatType, nullable = true) ::
      StructField("bureau_AMT_CREDIT_SUM_OVERDUE_mean", FloatType, nullable = true) ::
      StructField("bureau_AMT_CREDIT_SUM_OVERDUE_max", FloatType, nullable = true) ::
      StructField("bureau_AMT_CREDIT_SUM_OVERDUE_min", FloatType, nullable = true) ::
      StructField("bureau_DAYS_CREDIT_UPDATE_mean", FloatType, nullable = true) ::
      StructField("bureau_DAYS_CREDIT_UPDATE_max", FloatType, nullable = true) ::
      StructField("bureau_DAYS_CREDIT_UPDATE_min", FloatType, nullable = true) ::
      StructField("bureau_AMT_ANNUITY_count", FloatType, nullable = true) ::
      StructField("bureau_AMT_ANNUITY_mean", FloatType, nullable = true) ::
      StructField("bureau_AMT_ANNUITY_max", FloatType, nullable = true) ::
      StructField("bureau_AMT_ANNUITY_min", FloatType, nullable = true) ::
      Nil)

  val schemaPart3 = StructType(
    StructField("client_bureau_balance_MONTHS_BALANCE_count_mean", FloatType, nullable = true) ::
      StructField("client_bureau_balance_MONTHS_BALANCE_count_min", FloatType, nullable = true) ::
      StructField("client_bureau_balance_MONTHS_BALANCE_max_mean", FloatType, nullable = true) ::
      StructField("client_bureau_balance_MONTHS_BALANCE_max_max", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_0_count_mean", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_0_count_max", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_0_count_min", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_0_count_sum", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_0_count_norm_mean", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_0_count_norm_max", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_0_count_norm_min", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_0_count_norm_sum", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_1_count_mean", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_1_count_max", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_1_count_min", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_1_count_norm_mean", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_1_count_norm_max", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_1_count_norm_min", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_2_count_mean", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_2_count_max", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_2_count_min", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_2_count_norm_mean", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_2_count_norm_min", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_3_count_mean", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_3_count_max", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_3_count_min", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_3_count_norm_mean", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_3_count_norm_min", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_4_count_mean", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_4_count_max", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_4_count_min", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_4_count_sum", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_4_count_norm_min", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_5_count_mean", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_5_count_max", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_5_count_min", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_C_count_mean", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_C_count_min", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_C_count_norm_max", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_X_count_mean", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_X_count_max", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_X_count_min", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_X_count_norm_mean", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_X_count_norm_max", FloatType, nullable = true) ::
      StructField("client_bureau_balance_STATUS_X_count_norm_min", FloatType, nullable = true) ::
      Nil)

  val schemaPart4 = StructType(
      StructField("credit_card_balance_NAME_CONTRACT_STATUS_Active_count", FloatType, nullable = true) ::
      StructField("credit_card_balance_NAME_CONTRACT_STATUS_Active_count_norm", FloatType, nullable = true) ::
      StructField("credit_card_balance_NAME_CONTRACT_STATUS_Approved_count", FloatType, nullable = true) ::
      StructField("credit_card_balance_NAME_CONTRACT_STATUS_Completed_count", FloatType, nullable = true) ::
      StructField("credit_card_balance_NAME_CONTRACT_STATUS_Completed_count_norm", FloatType, nullable = true) ::
      StructField("credit_card_balance_NAME_CONTRACT_STATUS_Demand_count", FloatType, nullable = true) ::
      StructField("credit_card_balance_NAME_CONTRACT_STATUS_Refused_count", FloatType, nullable = true) ::
      StructField("credit_card_balance_NAME_CONTRACT_STATUS_Sent_proposal_count", FloatType, nullable = true) ::
      StructField("credit_card_balance_NAME_CONTRACT_STATUS_Signed_count", FloatType, nullable = true) ::
      StructField("credit_card_balance_NAME_CONTRACT_STATUS_Signed_count_norm", FloatType, nullable = true) ::
      StructField("credit_card_balance_MONTHS_BALANCE_mean", FloatType, nullable = true) ::
      StructField("credit_card_balance_MONTHS_BALANCE_max", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_BALANCE_mean", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_BALANCE_min", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_BALANCE_sum", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_CREDIT_LIMIT_ACTUAL_mean", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_CREDIT_LIMIT_ACTUAL_sum", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_DRAWINGS_ATM_CURRENT_mean", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_DRAWINGS_ATM_CURRENT_max", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_DRAWINGS_ATM_CURRENT_min", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_DRAWINGS_ATM_CURRENT_sum", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_DRAWINGS_CURRENT_mean", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_DRAWINGS_CURRENT_min", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_DRAWINGS_CURRENT_sum", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_DRAWINGS_OTHER_CURRENT_mean", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_DRAWINGS_OTHER_CURRENT_max", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_DRAWINGS_OTHER_CURRENT_min", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_DRAWINGS_POS_CURRENT_mean", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_DRAWINGS_POS_CURRENT_max", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_DRAWINGS_POS_CURRENT_min", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_INST_MIN_REGULARITY_min", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_PAYMENT_CURRENT_max", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_PAYMENT_CURRENT_min", FloatType, nullable = true) ::
      StructField("credit_card_balance_AMT_PAYMENT_TOTAL_CURRENT_min", FloatType, nullable = true) ::
      StructField("credit_card_balance_CNT_DRAWINGS_ATM_CURRENT_mean", FloatType, nullable = true) ::
      StructField("credit_card_balance_CNT_DRAWINGS_ATM_CURRENT_max", FloatType, nullable = true) ::
      StructField("credit_card_balance_CNT_DRAWINGS_ATM_CURRENT_sum", FloatType, nullable = true) ::
      StructField("credit_card_balance_CNT_DRAWINGS_CURRENT_mean", FloatType, nullable = true) ::
      StructField("credit_card_balance_CNT_DRAWINGS_CURRENT_min", FloatType, nullable = true) ::
      StructField("credit_card_balance_CNT_DRAWINGS_OTHER_CURRENT_mean", FloatType, nullable = true) ::
      StructField("credit_card_balance_CNT_DRAWINGS_OTHER_CURRENT_max", FloatType, nullable = true) ::
      StructField("credit_card_balance_CNT_DRAWINGS_OTHER_CURRENT_sum", FloatType, nullable = true) ::
      StructField("credit_card_balance_CNT_DRAWINGS_POS_CURRENT_min", FloatType, nullable = true) ::
      StructField("credit_card_balance_CNT_INSTALMENT_MATURE_CUM_min", FloatType, nullable = true) ::
      StructField("credit_card_balance_SK_DPD_mean", FloatType, nullable = true) ::
      StructField("credit_card_balance_SK_DPD_min", FloatType, nullable = true) ::
      StructField("credit_card_balance_SK_DPD_DEF_mean", FloatType, nullable = true) ::
      StructField("credit_card_balance_SK_DPD_DEF_min", FloatType, nullable = true) ::
      StructField("POS_cash_balance_NAME_CONTRACT_STATUS_Active_count", FloatType, nullable = true) ::
      StructField("POS_cash_balance_NAME_CONTRACT_STATUS_Active_count_norm", FloatType, nullable = true) ::
      StructField("POS_cash_balance_NAME_CONTRACT_STATUS_Amortized_debt_count", FloatType, nullable = true) ::
      StructField("POS_cash_balance_NAME_CONTRACT_STATUS_Approved_count", FloatType, nullable = true) ::
      StructField("POS_cash_balance_NAME_CONTRACT_STATUS_Approved_count_norm", FloatType, nullable = true) ::
      StructField("POS_cash_balance_NAME_CONTRACT_STATUS_Canceled_count", FloatType, nullable = true) ::
      StructField("POS_cash_balance_NAME_CONTRACT_STATUS_Canceled_count_norm", FloatType, nullable = true) ::
      StructField("POS_cash_balance_NAME_CONTRACT_STATUS_Completed_count", FloatType, nullable = true) ::
      StructField("POS_cash_balance_NAME_CONTRACT_STATUS_Completed_count_norm", FloatType, nullable = true) ::
      StructField("POS_cash_balance_NAME_CONTRACT_STATUS_Demand_count", FloatType, nullable = true) ::
      StructField("POS_cash_balance_NAME_CONTRACT_STATUS_Returned_to_the_store_count", FloatType, nullable = true) ::
      StructField("POS_cash_balance_NAME_CONTRACT_STATUS_Returned_to_the_store_count_norm", FloatType, nullable = true) ::
      StructField("POS_cash_balance_NAME_CONTRACT_STATUS_Signed_count", FloatType, nullable = true) ::
      StructField("POS_cash_balance_NAME_CONTRACT_STATUS_Signed_count_norm", FloatType, nullable = true) ::
      StructField("POS_cash_balance_NAME_CONTRACT_STATUS_XNA_count", FloatType, nullable = true) ::
      StructField("POS_cash_balance_MONTHS_BALANCE_mean", FloatType, nullable = true) ::
      StructField("POS_cash_balance_MONTHS_BALANCE_max", FloatType, nullable = true) ::
      StructField("POS_cash_balance_MONTHS_BALANCE_sum", FloatType, nullable = true) ::
      StructField("POS_cash_balance_CNT_INSTALMENT_mean", FloatType, nullable = true) ::
      StructField("POS_cash_balance_CNT_INSTALMENT_min", FloatType, nullable = true) ::
      StructField("POS_cash_balance_CNT_INSTALMENT_FUTURE_min", FloatType, nullable = true) ::
      StructField("POS_cash_balance_SK_DPD_mean", FloatType, nullable = true) ::
      StructField("POS_cash_balance_SK_DPD_min", FloatType, nullable = true) ::
      StructField("POS_cash_balance_SK_DPD_DEF_mean", FloatType, nullable = true) ::
      StructField("POS_cash_balance_SK_DPD_DEF_min", FloatType, nullable = true) ::
      Nil)

  val schemaPart5 = StructType(
    StructField("installments_payments_NUM_INSTALMENT_VERSION_count", FloatType, nullable = true) ::
      StructField("installments_payments_NUM_INSTALMENT_VERSION_mean", FloatType, nullable = true) ::
      StructField("installments_payments_NUM_INSTALMENT_VERSION_max", FloatType, nullable = true) ::
      StructField("installments_payments_NUM_INSTALMENT_VERSION_min", FloatType, nullable = true) ::
      StructField("installments_payments_NUM_INSTALMENT_VERSION_sum", FloatType, nullable = true) ::
      StructField("installments_payments_NUM_INSTALMENT_NUMBER_min", FloatType, nullable = true) ::
      StructField("installments_payments_AMT_INSTALMENT_mean", FloatType, nullable = true) ::
      StructField("installments_payments_AMT_INSTALMENT_max", FloatType, nullable = true) ::
      StructField("installments_payments_AMT_INSTALMENT_min", FloatType, nullable = true) ::
      StructField("installments_payments_AMT_INSTALMENT_sum", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CONTRACT_TYPE_Cash_loans_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CONTRACT_TYPE_Cash_loans_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CONTRACT_TYPE_Consumer_loans_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CONTRACT_TYPE_Consumer_loans_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CONTRACT_TYPE_Revolving_loans_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CONTRACT_TYPE_Revolving_loans_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CONTRACT_TYPE_XNA_count", FloatType, nullable = true) ::
      StructField("previous_application_WEEKDAY_APPR_PROCESS_START_FRIDAY_count", FloatType, nullable = true) ::
      StructField("previous_application_WEEKDAY_APPR_PROCESS_START_FRIDAY_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_WEEKDAY_APPR_PROCESS_START_MONDAY_count", FloatType, nullable = true) ::
      StructField("previous_application_WEEKDAY_APPR_PROCESS_START_MONDAY_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_WEEKDAY_APPR_PROCESS_START_SATURDAY_count", FloatType, nullable = true) ::
      StructField("previous_application_WEEKDAY_APPR_PROCESS_START_SATURDAY_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_WEEKDAY_APPR_PROCESS_START_SUNDAY_count", FloatType, nullable = true) ::
      StructField("previous_application_WEEKDAY_APPR_PROCESS_START_SUNDAY_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_WEEKDAY_APPR_PROCESS_START_THURSDAY_count", FloatType, nullable = true) ::
      StructField("previous_application_WEEKDAY_APPR_PROCESS_START_THURSDAY_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_WEEKDAY_APPR_PROCESS_START_TUESDAY_count", FloatType, nullable = true) ::
      StructField("previous_application_WEEKDAY_APPR_PROCESS_START_TUESDAY_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_WEEKDAY_APPR_PROCESS_START_WEDNESDAY_count", FloatType, nullable = true) ::
      StructField("previous_application_WEEKDAY_APPR_PROCESS_START_WEDNESDAY_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_FLAG_LAST_APPL_PER_CONTRACT_N_count", FloatType, nullable = true) ::
      StructField("previous_application_FLAG_LAST_APPL_PER_CONTRACT_Y_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Building_a_house_or_an_annex_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Building_a_house_or_an_annex_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Business_development_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Business_development_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Buying_a_garage_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Buying_a_garage_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Buying_a_holiday_home___land_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Buying_a_holiday_home___land_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Buying_a_home_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Buying_a_home_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Buying_a_new_car_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Buying_a_new_car_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Buying_a_used_car_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Buying_a_used_car_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Car_repairs_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Car_repairs_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Education_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Education_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Everyday_expenses_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Everyday_expenses_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Furniture_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Furniture_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Gasification___water_supply_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Gasification___water_supply_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Hobby_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Journey_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Journey_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Medicine_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Medicine_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Money_for_a_third_person_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Money_for_a_third_person_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Other_count", FloatType, nullable = true) ::
      Nil)

  val schemaPart6 = StructType(
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Other_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Payments_on_other_loans_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Payments_on_other_loans_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Purchase_of_electronic_equipment_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Purchase_of_electronic_equipment_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Refusal_to_name_the_goal_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Refusal_to_name_the_goal_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Repairs_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Repairs_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Urgent_needs_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Urgent_needs_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Wedding___gift___holiday_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CASH_LOAN_PURPOSE_Wedding___gift___holiday_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CONTRACT_STATUS_Approved_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CONTRACT_STATUS_Canceled_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CONTRACT_STATUS_Canceled_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CONTRACT_STATUS_Refused_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CONTRACT_STATUS_Refused_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CONTRACT_STATUS_Unused_offer_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_PAYMENT_TYPE_Cash_through_the_bank_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_PAYMENT_TYPE_Cashless_from_the_account_of_the_employer_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_PAYMENT_TYPE_Cashless_from_the_account_of_the_employer_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_PAYMENT_TYPE_Non_cash_from_your_account_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_PAYMENT_TYPE_Non_cash_from_your_account_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_PAYMENT_TYPE_XNA_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_CODE_REJECT_REASON_HC_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_CODE_REJECT_REASON_LIMIT_count", FloatType, nullable = true) ::
      StructField("previous_application_CODE_REJECT_REASON_LIMIT_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_CODE_REJECT_REASON_SCO_count", FloatType, nullable = true) ::
      StructField("previous_application_CODE_REJECT_REASON_SCO_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_CODE_REJECT_REASON_SCOFR_count", FloatType, nullable = true) ::
      StructField("previous_application_CODE_REJECT_REASON_SCOFR_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_CODE_REJECT_REASON_SYSTEM_count", FloatType, nullable = true) ::
      StructField("previous_application_CODE_REJECT_REASON_VERIF_count", FloatType, nullable = true) ::
      StructField("previous_application_CODE_REJECT_REASON_VERIF_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_CODE_REJECT_REASON_XAP_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_CODE_REJECT_REASON_XNA_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_TYPE_SUITE_Children_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_TYPE_SUITE_Children_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_TYPE_SUITE_Family_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_TYPE_SUITE_Family_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_TYPE_SUITE_Group_of_people_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_TYPE_SUITE_Group_of_people_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_TYPE_SUITE_Other_A_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_TYPE_SUITE_Other_A_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_TYPE_SUITE_Other_B_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_TYPE_SUITE_Other_B_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_TYPE_SUITE_Spouse__partner_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_TYPE_SUITE_Spouse__partner_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_TYPE_SUITE_Unaccompanied_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_TYPE_SUITE_Unaccompanied_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CLIENT_TYPE_New_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CLIENT_TYPE_New_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CLIENT_TYPE_Refreshed_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CLIENT_TYPE_Refreshed_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CLIENT_TYPE_Repeater_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CLIENT_TYPE_XNA_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_CLIENT_TYPE_XNA_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Additional_Service_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Additional_Service_count_norm", FloatType, nullable = true) ::
      Nil)

  val schemaPart7 = StructType(
    StructField("previous_application_NAME_GOODS_CATEGORY_Animals_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Audio_Video_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Audio_Video_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Auto_Accessories_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Auto_Accessories_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Clothing_and_Accessories_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Clothing_and_Accessories_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Computers_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Computers_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Construction_Materials_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Construction_Materials_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Consumer_Electronics_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Consumer_Electronics_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Direct_Sales_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Direct_Sales_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Education_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Education_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Fitness_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Fitness_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Furniture_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Furniture_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Gardening_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Gardening_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Homewares_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Homewares_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_House_Construction_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_House_Construction_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Insurance_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Insurance_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Jewelry_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Jewelry_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Medical_Supplies_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Medical_Supplies_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Medicine_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Medicine_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Mobile_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Mobile_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Office_Appliances_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Office_Appliances_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Other_count", FloatType, nullable = true) ::
      Nil)

  val schemaPart8 = StructType(
      StructField("previous_application_NAME_GOODS_CATEGORY_Other_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Photo___Cinema_Equipment_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Photo___Cinema_Equipment_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Sport_and_Leisure_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Sport_and_Leisure_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Tourism_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Tourism_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Vehicles_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Vehicles_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Weapon_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_GOODS_CATEGORY_Weapon_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_PORTFOLIO_Cars_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_PRODUCT_TYPE_walk_in_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_PRODUCT_TYPE_walk_in_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_PRODUCT_TYPE_x_sell_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_CHANNEL_TYPE_AP___Cash_loan__count", FloatType, nullable = true) ::
      StructField("previous_application_CHANNEL_TYPE_AP___Cash_loan__count_norm", FloatType, nullable = true) ::
      StructField("previous_application_CHANNEL_TYPE_Channel_of_corporate_sales_count", FloatType, nullable = true) ::
      StructField("previous_application_CHANNEL_TYPE_Channel_of_corporate_sales_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_CHANNEL_TYPE_Contact_center_count", FloatType, nullable = true) ::
      StructField("previous_application_CHANNEL_TYPE_Contact_center_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_CHANNEL_TYPE_Country_wide_count", FloatType, nullable = true) ::
      StructField("previous_application_CHANNEL_TYPE_Country_wide_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_CHANNEL_TYPE_Credit_and_cash_offices_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_CHANNEL_TYPE_Regional___Local_count", FloatType, nullable = true) ::
      StructField("previous_application_CHANNEL_TYPE_Regional___Local_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_CHANNEL_TYPE_Stone_count", FloatType, nullable = true) ::
      StructField("previous_application_CHANNEL_TYPE_Stone_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_SELLER_INDUSTRY_Auto_technology_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_SELLER_INDUSTRY_Auto_technology_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_SELLER_INDUSTRY_Construction_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_SELLER_INDUSTRY_Construction_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_SELLER_INDUSTRY_Consumer_electronics_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_SELLER_INDUSTRY_Consumer_electronics_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_SELLER_INDUSTRY_Industry_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_SELLER_INDUSTRY_Industry_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_SELLER_INDUSTRY_Jewelry_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_SELLER_INDUSTRY_Jewelry_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_SELLER_INDUSTRY_MLM_partners_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_SELLER_INDUSTRY_MLM_partners_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_SELLER_INDUSTRY_Tourism_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_SELLER_INDUSTRY_Tourism_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_YIELD_GROUP_high_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_YIELD_GROUP_high_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_YIELD_GROUP_low_action_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_YIELD_GROUP_low_action_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_YIELD_GROUP_low_normal_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_YIELD_GROUP_low_normal_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_NAME_YIELD_GROUP_middle_count", FloatType, nullable = true) ::
      StructField("previous_application_NAME_YIELD_GROUP_middle_count_norm", FloatType, nullable = true) ::
      Nil)

  val schemaPart9 = StructType(
    StructField("previous_application_PRODUCT_COMBINATION_Card_X_Sell_count", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_Cash_Street__high_count", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_Cash_Street__high_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_Cash_Street__low_count", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_Cash_Street__low_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_Cash_Street__middle_count", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_Cash_Street__middle_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_Cash_X_Sell__high_count", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_Cash_X_Sell__high_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_Cash_X_Sell__low_count", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_Cash_X_Sell__low_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_Cash_X_Sell__middle_count", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_Cash_X_Sell__middle_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_POS_household_with_interest_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_POS_household_without_interest_count", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_POS_household_without_interest_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_POS_industry_with_interest_count", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_POS_industry_with_interest_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_POS_industry_without_interest_count", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_POS_industry_without_interest_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_POS_mobile_without_interest_count", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_POS_mobile_without_interest_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_POS_other_with_interest_count", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_POS_other_with_interest_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_POS_others_without_interest_count", FloatType, nullable = true) ::
      StructField("previous_application_PRODUCT_COMBINATION_POS_others_without_interest_count_norm", FloatType, nullable = true) ::
      StructField("previous_application_AMT_ANNUITY_mean", FloatType, nullable = true) ::
      StructField("previous_application_AMT_ANNUITY_min", FloatType, nullable = true) ::
      StructField("previous_application_AMT_ANNUITY_sum", FloatType, nullable = true) ::
      StructField("previous_application_AMT_APPLICATION_mean", FloatType, nullable = true) ::
      StructField("previous_application_AMT_APPLICATION_min", FloatType, nullable = true) ::
      StructField("previous_application_AMT_DOWN_PAYMENT_mean", FloatType, nullable = true) ::
      StructField("previous_application_AMT_GOODS_PRICE_min", FloatType, nullable = true) ::
      StructField("previous_application_HOUR_APPR_PROCESS_START_mean", FloatType, nullable = true) ::
      StructField("previous_application_NFLAG_LAST_APPL_IN_DAY_mean", FloatType, nullable = true) ::
      StructField("previous_application_NFLAG_LAST_APPL_IN_DAY_max", FloatType, nullable = true) ::
      StructField("previous_application_NFLAG_LAST_APPL_IN_DAY_min", FloatType, nullable = true) ::
      StructField("previous_application_RATE_DOWN_PAYMENT_mean", FloatType, nullable = true) ::
      StructField("previous_application_RATE_INTEREST_PRIMARY_count", FloatType, nullable = true) ::
      StructField("previous_application_DAYS_DECISION_max", FloatType, nullable = true) ::
      StructField("previous_application_DAYS_DECISION_sum", FloatType, nullable = true) ::
      StructField("previous_application_SELLERPLACE_AREA_mean", FloatType, nullable = true) ::
      StructField("previous_application_SELLERPLACE_AREA_max", FloatType, nullable = true) ::
      StructField("previous_application_CNT_PAYMENT_mean", FloatType, nullable = true) ::
      StructField("previous_application_CNT_PAYMENT_min", FloatType, nullable = true) ::
      StructField("previous_application_DAYS_FIRST_DRAWING_mean", FloatType, nullable = true) ::
      StructField("previous_application_DAYS_FIRST_DRAWING_max", FloatType, nullable = true) ::
      StructField("previous_application_DAYS_FIRST_DUE_mean", FloatType, nullable = true) ::
      StructField("previous_application_DAYS_FIRST_DUE_min", FloatType, nullable = true) ::
      StructField("previous_application_DAYS_LAST_DUE_1ST_VERSION_mean", FloatType, nullable = true) ::
      StructField("previous_application_DAYS_LAST_DUE_1ST_VERSION_min", FloatType, nullable = true) ::
      StructField("previous_application_DAYS_LAST_DUE_mean", FloatType, nullable = true) ::
      StructField("previous_application_DAYS_LAST_DUE_max", FloatType, nullable = true) ::
      StructField("previous_application_DAYS_LAST_DUE_min", FloatType, nullable = true) ::
      StructField("previous_application_NFLAG_INSURED_ON_APPROVAL_mean", FloatType, nullable = true) ::
      StructField("previous_application_NFLAG_INSURED_ON_APPROVAL_min", FloatType, nullable = true) ::
      StructField("previous_application_NFLAG_INSURED_ON_APPROVAL_sum", FloatType, nullable = true) ::
      Nil
  )

  val trainSchema: StructType = StructType(trainSchemaHeader ++ schemaPart0 ++ schemaPart1 ++ schemaPart2 ++ schemaPart3 ++ schemaPart4 ++ schemaPart5 ++ schemaPart6 ++ schemaPart7 ++ schemaPart8 ++ schemaPart9)
  val testSchema: StructType = StructType(testSchemaHeader ++ schemaPart0 ++ schemaPart1 ++ schemaPart2 ++ schemaPart3 ++ schemaPart4 ++ schemaPart5 ++ schemaPart6 ++ schemaPart7 ++ schemaPart8 ++ schemaPart9)

  def encodeStringColumns(inputDF: DataFrame):DataFrame = {
    var dfIndexed: DataFrame = inputDF
    val NAME_CONTRACT_TYPEIndexer = new StringIndexer().setInputCol("NAME_CONTRACT_TYPE").setOutputCol("NAME_CONTRACT_TYPEIndex").setHandleInvalid("keep")
    dfIndexed = NAME_CONTRACT_TYPEIndexer.fit(dfIndexed).transform(dfIndexed)
    val CODE_GENDERIndexer = new StringIndexer().setInputCol("CODE_GENDER").setOutputCol("CODE_GENDERIndex").setHandleInvalid("keep")
    dfIndexed = CODE_GENDERIndexer.fit(dfIndexed).transform(dfIndexed)
    val FLAG_OWN_CARIndexer = new StringIndexer().setInputCol("FLAG_OWN_CAR").setOutputCol("FLAG_OWN_CARIndex").setHandleInvalid("keep")
    dfIndexed = FLAG_OWN_CARIndexer.fit(dfIndexed).transform(dfIndexed)
    val FLAG_OWN_REALTYIndexer = new StringIndexer().setInputCol("FLAG_OWN_REALTY").setOutputCol("FLAG_OWN_REALTYIndex").setHandleInvalid("keep")
    dfIndexed = FLAG_OWN_REALTYIndexer.fit(dfIndexed).transform(dfIndexed)
    val NAME_TYPE_SUITEIndexer = new StringIndexer().setInputCol("NAME_TYPE_SUITE").setOutputCol("NAME_TYPE_SUITEIndex").setHandleInvalid("keep")
    dfIndexed = NAME_TYPE_SUITEIndexer.fit(dfIndexed).transform(dfIndexed)
    val NAME_INCOME_TYPEIndexer = new StringIndexer().setInputCol("NAME_INCOME_TYPE").setOutputCol("NAME_INCOME_TYPEIndex").setHandleInvalid("keep")
    dfIndexed = NAME_INCOME_TYPEIndexer.fit(dfIndexed).transform(dfIndexed)
    val NAME_EDUCATION_TYPEIndexer = new StringIndexer().setInputCol("NAME_EDUCATION_TYPE").setOutputCol("NAME_EDUCATION_TYPEIndex").setHandleInvalid("keep")
    dfIndexed = NAME_EDUCATION_TYPEIndexer.fit(dfIndexed).transform(dfIndexed)
    val NAME_FAMILY_STATUSIndexer = new StringIndexer().setInputCol("NAME_FAMILY_STATUS").setOutputCol("NAME_FAMILY_STATUSIndex").setHandleInvalid("keep")
    dfIndexed = NAME_FAMILY_STATUSIndexer.fit(dfIndexed).transform(dfIndexed)
    val NAME_HOUSING_TYPEIndexer = new StringIndexer().setInputCol("NAME_HOUSING_TYPE").setOutputCol("NAME_HOUSING_TYPEIndex").setHandleInvalid("keep")
    dfIndexed = NAME_HOUSING_TYPEIndexer.fit(dfIndexed).transform(dfIndexed)
    val OCCUPATION_TYPEIndexer = new StringIndexer().setInputCol("OCCUPATION_TYPE").setOutputCol("OCCUPATION_TYPEIndex").setHandleInvalid("keep")
    dfIndexed = OCCUPATION_TYPEIndexer.fit(dfIndexed).transform(dfIndexed)
    val WEEKDAY_APPR_PROCESS_STARTIndexer = new StringIndexer().setInputCol("WEEKDAY_APPR_PROCESS_START").setOutputCol("WEEKDAY_APPR_PROCESS_STARTIndex").setHandleInvalid("keep")
    dfIndexed = WEEKDAY_APPR_PROCESS_STARTIndexer.fit(dfIndexed).transform(dfIndexed)
    val ORGANIZATION_TYPEIndexer = new StringIndexer().setInputCol("ORGANIZATION_TYPE").setOutputCol("ORGANIZATION_TYPEIndex").setHandleInvalid("keep")
    dfIndexed = ORGANIZATION_TYPEIndexer.fit(dfIndexed).transform(dfIndexed)
    val FONDKAPREMONT_MODEIndexer = new StringIndexer().setInputCol("FONDKAPREMONT_MODE").setOutputCol("FONDKAPREMONT_MODEIndex").setHandleInvalid("keep")
    dfIndexed = FONDKAPREMONT_MODEIndexer.fit(dfIndexed).transform(dfIndexed)
    val HOUSETYPE_MODEIndexer = new StringIndexer().setInputCol("HOUSETYPE_MODE").setOutputCol("HOUSETYPE_MODEIndex").setHandleInvalid("keep")
    dfIndexed = HOUSETYPE_MODEIndexer.fit(dfIndexed).transform(dfIndexed)
    val WALLSMATERIAL_MODEIndexer = new StringIndexer().setInputCol("WALLSMATERIAL_MODE").setOutputCol("WALLSMATERIAL_MODEIndex").setHandleInvalid("keep")
    dfIndexed = WALLSMATERIAL_MODEIndexer.fit(dfIndexed).transform(dfIndexed)
    val EMERGENCYSTATE_MODEIndexer = new StringIndexer().setInputCol("EMERGENCYSTATE_MODE").setOutputCol("EMERGENCYSTATE_MODEIndex").setHandleInvalid("keep")
    dfIndexed = EMERGENCYSTATE_MODEIndexer.fit(dfIndexed).transform(dfIndexed)

    dfIndexed = dfIndexed.drop(
      "NAME_CONTRACT_TYPE",
      "CODE_GENDER",
      "FLAG_OWN_CAR",
      "FLAG_OWN_REALTY",
      "NAME_TYPE_SUITE",
      "NAME_INCOME_TYPE",
      "NAME_EDUCATION_TYPE",
      "NAME_FAMILY_STATUS",
      "NAME_HOUSING_TYPE",
      "OCCUPATION_TYPE",
      "WEEKDAY_APPR_PROCESS_START",
      "ORGANIZATION_TYPE",
      "FONDKAPREMONT_MODE",
      "HOUSETYPE_MODE",
      "WALLSMATERIAL_MODE",
      "EMERGENCYSTATE_MODE")

    dfIndexed
  }
}
